# Generated by Django 5.1.1 on 2024-10-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(unique=True, verbose_name='Tarih')),
                ('processed', models.BooleanField(default=False, verbose_name='İşlendi mi?')),
                ('data', models.JSONField(default=dict, verbose_name='Maç Verileri')),
                ('isData', models.BooleanField(default=False, verbose_name='Veri Var mi?')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
    ]
