# Generated by Django 5.1.1 on 2024-10-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Maç ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='İstatistikler')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.DeleteModel(
            name='FixtureData',
        ),
    ]
