# Generated by Django 5.1.1 on 2024-10-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_matchinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='season_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
