# Generated by Django 5.1.1 on 2024-10-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_teamperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPerformance',
        ),
    ]
