# Generated by Django 5.1.1 on 2024-10-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_delete_teamperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchInfo',
        ),
        migrations.DeleteModel(
            name='MatchStats',
        ),
        migrations.DeleteModel(
            name='PlayerPerformance',
        ),
    ]
