# Generated by Django 4.2.7 on 2024-10-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basemodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startTimestamp', models.DateTimeField()),
                ('slug', models.SlugField(max_length=255)),
                ('roundInfo_round', models.IntegerField()),
                ('status_type', models.CharField(max_length=50)),
                ('homeScore_current', models.IntegerField()),
                ('homeScore_period1', models.IntegerField()),
                ('homeScore_period2', models.IntegerField()),
                ('homeScore_normaltime', models.IntegerField()),
                ('awayScore_current', models.IntegerField()),
                ('awayScore_period1', models.IntegerField()),
                ('awayScore_period2', models.IntegerField()),
                ('awayScore_normaltime', models.IntegerField()),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='basemodels.team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='basemodels.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.season')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.tournament')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'unique_together': {('homeTeam', 'awayTeam', 'season', 'tournament')},
            },
        ),
    ]
