# Generated by Django 4.2.7 on 2024-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiztest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineups',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='percentvalue',
            name='statistics_item',
        ),
        migrations.RemoveField(
            model_name='period',
            name='match',
        ),
        migrations.RemoveField(
            model_name='statisticsitem',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='PercentValue',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='StatisticsItem',
        ),
    ]
