# Generated by Django 5.1.1 on 2024-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_tournament_season_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='season_id',
            field=models.IntegerField(verbose_name='Sezon ID'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('season_id', 'tournament_id'), name='unique_season_tournament'),
        ),
    ]
