# Generated by Django 5.1.1 on 2024-09-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_tournament_season_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='unique_season_tournament',
        ),
    ]
