# Generated by Django 5.1.1 on 2024-09-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_tournament_unique_season_tournament'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('season_id', 'tournament_id', 'tournament_name', 'season_name'), name='unique_season_tournament'),
        ),
    ]
