# Generated by Django 5.1.1 on 2024-09-22 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_tournament_unique_season_tournament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.BigIntegerField()),
                ('startTimestamp', models.BigIntegerField()),
                ('tournament_name', models.CharField(max_length=255)),
                ('tournament_category_name', models.CharField(max_length=255)),
                ('tournament_category_id', models.IntegerField()),
                ('tournament_uniqueTournament_name', models.CharField(max_length=255)),
                ('tournament_uniqueTournament_id', models.IntegerField()),
                ('season_name', models.CharField(max_length=255)),
                ('season_year', models.CharField(max_length=20)),
                ('season_id', models.IntegerField()),
                ('roundInfo_round', models.IntegerField()),
                ('status_type', models.CharField(max_length=50)),
                ('homeTeam_name', models.CharField(max_length=255)),
                ('homeTeam_nameCode', models.CharField(max_length=10)),
                ('homeTeam_id', models.IntegerField()),
                ('awayTeam_name', models.CharField(max_length=255)),
                ('awayTeam_nameCode', models.CharField(max_length=10)),
                ('awayTeam_id', models.IntegerField()),
                ('homeScore_period1', models.IntegerField()),
                ('homeScore_period2', models.IntegerField()),
                ('homeScore_normaltime', models.IntegerField()),
                ('awayScore_period1', models.IntegerField()),
                ('awayScore_period2', models.IntegerField()),
                ('awayScore_normaltime', models.IntegerField()),
                ('UpdateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idx', 'season_id'), name='match_unique')],
            },
        ),
        migrations.CreateModel(
            name='RoundinfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('current', models.IntegerField()),
                ('week', models.CharField(max_length=50)),
                ('last', models.IntegerField()),
                ('tournament_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('UpdateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'season_id', 'tournament_id'), name='unique_week_tournament')],
            },
        ),
    ]
