# Generated by Django 5.1.1 on 2024-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_matchinfo_roundinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundinfoErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
