# Generated by Django 5.1.1 on 2024-10-19 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_uniqueTournament_id', models.IntegerField()),
                ('tournament_name', models.CharField(max_length=255)),
                ('tournament_slug', models.CharField(max_length=255)),
                ('tournament_category_name', models.CharField(max_length=255)),
                ('tournament_category_slug', models.CharField(max_length=255)),
                ('tournament_uniqueTournament_category_id', models.IntegerField()),
                ('tournament_uniqueTournament_hasEventPlayerStatistics', models.BooleanField(default=False)),
                ('tournament_id', models.IntegerField()),
                ('tournament_isGroup', models.BooleanField(blank=True, default=False, null=True)),
                ('tournament_uniqueTournament_hasPerformanceGraphFeature', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('season_name', models.CharField(max_length=255)),
                ('season_year', models.CharField(max_length=9)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='mymodel.tournament')),
            ],
        ),
    ]
